language: java
required: sudo
addons:
  apt:
    packages:
      - xvfb
      - maven
before_install:
  - sudo apt-get -qq update || echo no sudo apt-get
  - sudo apt-get install openjdk-11-jdk
  - sudo apt-get install libopenjfx-jni
  - sudo apt-get install -y libwebkitgtk-3.0-0 || echo no sudo apt-get
  - sudo apt-get install -y xdg-utils || echo no xdg-utils
before_script:
  - export DISPLAY=:1
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64
  - export PATH=$PATH:$JAVA_HOME/bin
  - export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/jni/:$LD_LIBRARY_PATH
  - /usr/bin/Xvfb :1 -screen 0 1024x768x24 &
  - sleep 9
script:
  - mvn install -DskipTests
  - mvn -f $TEST_SUITE-archetype-test verify
dist: trusty
osx_image: xcode9.3
os:
  - linux
  - osx
arch:
  - amd64
  - arm64
env:
  - TEST_SUITE=ko
  - TEST_SUITE=crud
  - TEST_SUITE=visual
matrix:
  exclude:
    - os: osx
      jdk: oraclejdk8
